services:
  # Postgres (pgvector)
  pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql # docker volume for storage
    env_file:
      - ./env/.env.postgres
    networks:
      - backend
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Prometheus PostgreSQL exporter for postgres metrics
  pgvector_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pgvector_exporter
    ports:
      - "9187:9187"
    env_file:
      - ./env/.env.postgres-exporter
    networks:
      - backend
    restart: always
    depends_on:
      pgvector:
        condition: service_healthy

  # Qdrant (vector database)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always

  # Prometheus (monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # override default config
    networks:
      - backend
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle" # enable reload endpoint

      
  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./env/.env.grafana
    networks:
      - backend 
    restart: always

